bool data_ready                     # Indicates if sensor is connected and data has been recieved.
builtin_interfaces/Time timestamp   # Timestamp indicating when the sensor reading was recorded.
float64 force_x                     # Force in the x-direction (Newtons)
float64 force_y                     # Force in the y-direction (Newtons)
float64 force_z                     # Force in the z-direction (Netwons)